{% set name = "polylaue" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PolyLaue/PolyLaue/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1b27a34de81b1229fdd42d98fd188c21a151c63c133b5d5cf669b41d0ab3ede1

build:
  entry_points:
    - polylaue = polylaue.main:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
  run:
    - fabio
    - h5py
    - numba
    - numpy
    - pillow
    - platformdirs
    - pyqtgraph
    - pyside6
    - python >=3.10
    - scipy

test:
  imports:
    - polylaue
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PolyLaue/PolyLaue
  summary: A tool for visualizing and analyzing scans of Laue x-ray diffraction patterns
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vicentebolea
