{% set python_min = "3.11" %}
{% set name = "polylaue" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PolyLaue/PolyLaue/archive/refs/tags/{{ version }}.tar.gz
  sha256: e342d2a695689e2a9de5a2ed52b26869c829a7e57ec939cb9d3f6439b403327f

build:
  entry_points:
    - polylaue = polylaue.main:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - fabio
    - h5py
    - numba
    - numpy
    - pillow
    - platformdirs
    - pyqtgraph
    - pyside6
    - python >={{ python_min }}
    - scikit-image
    - scipy

test:
  imports:
    - polylaue
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PolyLaue/PolyLaue
  summary: A tool for visualizing and analyzing scans of Laue x-ray diffraction patterns
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vicentebolea
    - psavery
